### ISSUE TITLE
Unhandled exception. System.ComponentModel.Win32Exception (2): The system cannot find the file specified.

### ISSUE THREAD

**Issue by danielok1993** [ModernRonin/ProjectRenamer#1]
When trying to rename a project I get the error above.

Stack trace:

Unhandled exception. System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at ModernRonin.ProjectRenamer.Program.RunTool(String tool, String arguments, Action onNonZeroExitCode) in C:\Projects\Github\ProjectRenaming\ModernRonin.ProjectRenamer\Program.cs:line 185
   at ModernRonin.ProjectRenamer.Program.<EnsureGitIsClean>g__run|3_0(String arguments) in C:\Projects\Github\ProjectRenaming\ModernRonin.ProjectRenamer\Program.cs:line 44
   at ModernRonin.ProjectRenamer.Program.EnsureGitIsClean() in C:\Projects\Github\ProjectRenaming\ModernRonin.ProjectRenamer\Program.cs:line 39
   at ModernRonin.ProjectRenamer.Program.Main(String[] args) in C:\Projects\Github\ProjectRenaming\ModernRonin.ProjectRenamer\Program.cs:line 32

**Comment by ModernRonin** [comment]
Do you have git in your PATH? That exception looks as if you don't. I'll add better error output for this, but the quick fix for you should be just to ensure that you can call git from your command-line by putting it into your PATH.

**Comment by ModernRonin** [comment]
there is now proper error reporting for this case and a new version 1.0.1 available
